### PR TITLE
Update pester.ps1

### PR DESCRIPTION
**Pull request by Clebam**
Add output to get Publish Test Result work on VSTS

### CODE REVIEW

**Comment by FriedrichWeinmann** [comment]
Heya, thanks for the revised version.
I just updated the build definition to also publish those test results, so triggering them now.
Would you mind doing a few changes?
- Store results in `<repositoryroot>\TestResults`. Just to be sure they aren't accidentally published to the gallery along with the module.
- Add a .gitignore entry that excludes test results, so they never accidentally end as items in the source control
When changing the path, please also be sure to make it a relative path to pester.ps1 - environment variables may not always apply since this can be executed both in VSTS and locally.

Finally: In order to retrigger the entire process, just update the branch on your fork. Github will notice the change and update the pull request, triggering the validation again.

**Comment by Clebam** [comment]
Done.

Tell me if it's ok. (There is also a commit linked to the Linux problem. I did not how to ignore it on this PR)

**Comment by Clebam** [comment]
In fact, I guess it's going to fail with VSTS since the TestResults directory does not exist in the repository.

I did something different that works ==> Creating the directory if it does not exist.

But I do not know if it may end up in the gallery when you build it.

You might see it here : https://github.com/Clebam/CentreonPowerShell/blob/Development/CentreonPowerShell/tests/pester.ps1

**Comment by FriedrichWeinmann** [comment]
Thanks a lot for that update! 👍

**Comment by Clebam** [comment]
I guess you should update line 57 too.  👍

**Pull request merged**
